#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : httpd
Version  : 2.4.18
Release  : 53
URL      : http://download.nextag.com/apache//httpd/httpd-2.4.18.tar.gz
Source0  : http://download.nextag.com/apache//httpd/httpd-2.4.18.tar.gz
Source1  : httpd.service
Source2  : httpd.tmpfiles
Summary  : Apache HTTP Server
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : apr-dev
BuildRequires : apr-util-dev
BuildRequires : cmake
BuildRequires : expat-dev
BuildRequires : openssl-dev
BuildRequires : pcre
BuildRequires : pcre-dev
BuildRequires : util-linux-dev
Patch1: 0001-default-config.patch
Patch2: 0002-do-not-crash-when-IncludeOptional-dir-is-not-existent.patch
Patch3: 0003-Look-fo-envvars-in-etc-httpd.patch

%description
Apache is a powerful, full-featured, efficient, and freely-available
Web server. Apache is also the most popular Web server on the
Internet.

%prep
%setup -q -n httpd-2.4.18
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export CFLAGS="$CFLAGS -fno-semantic-interposition -falign-functions=32 -flto -O3 "
export CXXFLAGS="$CXXFLAGS -fno-semantic-interposition -falign-functions=32 -flto -O3 "
%configure --disable-static --libdir=/usr/lib \
--sysconfdir=/usr/share/defaults/httpd \
--includedir=/usr/include/httpd \
--libexecdir=/usr/lib/httpd/modules \
--datadir=/usr/share/httpd \
--enable-mpms-shared=all \
--with-apr=/usr/bin/apr-1-config --with-apr-util=/usr/bin --with-mpm=worker \
--enable-pie \
--with-pcre \
--enable-mods-shared=all \
--enable-ssl --with-ssl --disable-distcache \
--disable-imagemap
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/httpd.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/tmpfiles.d/httpd.conf

%files
%defattr(-,root,root,-)
